### ISSUE TITLE
Issues after upgrading to Flutter 2.5.1

### ISSUE THREAD

**Issue by sukaper** [TabooSun/overlay_tutorial#28]
Hi. As the title says after the recent major flutter update, I've started having issues with the package.
After advancing the tutorial once by tapping the indicated zone, the overlay disappears and debug console starts getting spammed with error messages. 

Flutter version information:
```
    • Flutter version 2.5.1 at C:\bin\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (26 hours ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2
```
<details>
<summary>Logs</summary>

```
I/flutter (10861): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (10861): The following assertion was thrown during paint():
I/flutter (10861): Cannot get renderObject of inactive element.
I/flutter (10861): In order for an element to have a valid renderObject, it must be active, which means it is part of
I/flutter (10861): the tree.
I/flutter (10861): Instead, this element is in the _ElementLifecycle.inactive state.
I/flutter (10861): If you called this method from a State object, consider guarding it with State.mounted.
I/flutter (10861): The findRenderObject() method was called for the following element:
I/flutter (10861):   OverlayTutorialHole
I/flutter (10861):
I/flutter (10861): The relevant error-causing widget was:
I/flutter (10861):   OverlayTutorialScope
I/flutter (10861):   OverlayTutorialScope:file:///project_name_removed_for_privacy/lib/utils/tutorial_section.dart/tutorial_overlay.dart:181:22
I/flutter (10861):
I/flutter (10861): When the exception was thrown, this was the stack:
I/flutter (10861): #0      Element.findRenderObject.<anonymous closure>
package:flutter/…/widgets/framework.dart:3885
I/flutter (10861): #1      Element.findRenderObject
package:flutter/…/widgets/framework.dart:3898
I/flutter (10861): #2      OverlayTutorialScopeModel.computeRect
package:overlay_tutorial/…/model/overlay_tutorial_scope_model.dart:11
I/flutter (10861): #3      _RenderOverlayTutorialBackbone._calculateEntryRects.<anonymous closure>
package:overlay_tutorial/…/widgets/overlay_tutorial_scope.dart:342
I/flutter (10861): #4      Iterable.forEach (dart:core/iterable.dart:279:35)
I/flutter (10861): #5      _RenderOverlayTutorialBackbone._calculateEntryRects
package:overlay_tutorial/…/widgets/overlay_tutorial_scope.dart:341
I/flutter (10861): #6      _RenderOverlayTutorialBackbone._drawTutorialEntries
package:overlay_tutorial/…/widgets/overlay_tutorial_scope.dart:280
I/flutter (10861): #7      _RenderOverlayTutorialBackbone.paint
package:overlay_tutorial/…/widgets/overlay_tutorial_scope.dart:266
I/flutter (10861): #8      RenderObject._paintWithContext
package:flutter/…/rendering/object.dart:2409
I/flutter (10861): #9      PaintingContext.paintChild
package:flutter/…/rendering/object.dart:189
I/flutter (10861): #10     RenderBoxContainerDefaultsMixin.defaultPaint
package:flutter/…/rendering/box.dart:2794
I/flutter (10861): #11     RenderStack.paintStack
package:flutter/…/rendering/stack.dart:629
I/flutter (10861): #12     RenderStack.paint
package:flutter/…/rendering/stack.dart:645
I/flutter (10861): #13     RenderObject._paintWithContext
package:flutter/…/rendering/object.dart:2409
I/flutter (10861): #14     PaintingContext.paintChild
package:flutter/…/rendering/object.dart:189
I/flutter (10861): #15     RenderAnimatedOpacityMixin.paint
package:flutter/…/rendering/proxy_box.dart:1016
I/flutter (10861): #16     RenderObject._paintWithContext
package:flutter/…/rendering/object.dart:2409
I/flutter (10861): #17     PaintingContext.paintChild
package:flutter/…/rendering/object.dart:189
I/flutter (10861): #18     RenderBoxContainerDefaultsMixin.defaultPaint
package:flutter/…/rendering/box.dart:2794
I/flutter (10861): #19     RenderStack.paintStack
package:flutter/…/rendering/stack.dart:629
I/flutter (10861): #20     RenderStack.paint
package:flutter/…/rendering/stack.dart:645
I/flutter (10861): #21     RenderObject._paintWithContext
package:flutter/…/rendering/object.dart:2409
I/flutter (10861): #22     PaintingContext.paintChild
package:flutter/…/rendering/object.dart:189
I/flutter (10861): #23     RenderBoxContainerDefaultsMixin.defaultPaint
package:flutter/…/rendering/box.dart:2794
I/flutter (10861): #24     RenderStack.paintStack
package:flutter/…/rendering/stack.dart:629
I/flutter (10861): #25     RenderStack.paint
package:flutter/…/rendering/stack.dart:645
I/flutter (10861): #26     RenderObject._paintWithContext
package:flutter/…/rendering/object.dart:2409
I/flutter (10861): #27     PaintingContext.paintChild
package:flutter/…/rendering/object.dart:189
I/flutter (10861): #28     RenderBoxContainerDefaultsMixin.defaultPaint
package:flutter/…/rendering/box.dart:2794
I/flutter (10861): #29     RenderCustomMultiChildLayoutBox.paint
package:flutter/…/rendering/custom_layout.dart:409
I/flutter (10861): #30     RenderObject._paintWithContext
package:flutter/…/rendering/object.dart:2409
I/flutter (10861): #31     PaintingContext.paintChild
package:flutter/…/rendering/object.dart:189
I/flutter (10861): #32     RenderProxyBoxMixin.paint
package:flutter/…/rendering/proxy_box.dart:140
I/flutter (10861): #33     _RenderInkFeatures.paint
package:flutter/…/material/material.dart:553
I/flutter (10861): #34     RenderObject._paintWithContext
package:flutter/…/rendering/object.dart:2409
I/flutter (10861): #35     PaintingContext.paintChild
package:flutter/…/rendering/object.dart:189
I/flutter (10861): #36     RenderProxyBoxMixin.paint
package:flutter/…/rendering/proxy_box.dart:140
I/flutter (10861): #37     PaintingContext.pushLayer
package:flutter/…/rendering/object.dart:398
I/flutter (10861): #38     RenderPhysicalModel.paint
package:flutter/…/rendering/proxy_box.dart:1941
I/flutter (10861): #39     RenderObject._paintWithContext
package:flutter/…/rendering/object.dart:2409
I/flutter (10861): #40     PaintingContext.paintChild
package:flutter/…/rendering/object.dart:189
I/flutter (10861): #41     RenderProxyBoxMixin.paint
package:flutter/…/rendering/proxy_box.dart:140
I/flutter (10861): #42     RenderObject._paintWithContext
package:flutter/…/rendering/object.dart:2409
I/flutter (10861): #43     PaintingContext._repaintCompositedChild
package:flutter/…/rendering/object.dart:141
I/flutter (10861): #44     PaintingContext.repaintCompositedChild
package:flutter/…/rendering/object.dart:100
I/flutter (10861): #45     PipelineOwner.flushPaint
package:flutter/…/rendering/object.dart:979
I/flutter (10861): #46     RendererBinding.drawFrame
package:flutter/…/rendering/binding.dart:455
I/flutter (10861): #47     WidgetsBinding.drawFrame
package:flutter/…/widgets/binding.dart:883
I/flutter (10861): #48     RendererBinding._handlePersistentFrameCallback
package:flutter/…/rendering/binding.dart:319
I/flutter (10861): #49     SchedulerBinding._invokeFrameCallback
package:flutter/…/scheduler/binding.dart:1143
I/flutter (10861): #50     SchedulerBinding.handleDrawFrame
package:flutter/…/scheduler/binding.dart:1080
I/flutter (10861): #51     SchedulerBinding._handleDrawFrame
package:flutter/…/scheduler/binding.dart:996
I/flutter (10861): #55     _invoke (dart:ui/hooks.dart:166:10)
I/flutter (10861): #56     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270:5)
I/flutter (10861): #57     _drawFrame (dart:ui/hooks.dart:129:31)
I/flutter (10861): (elided 3 frames from dart:async)
I/flutter (10861):
I/flutter (10861): The following RenderObject was being processed when the exception was fired: _RenderOverlayTutorialBackbone#e10e2 relayoutBoundary=up5:
I/flutter (10861):   needs compositing
I/flutter (10861):   creator: _OverlayTutorialBackbone ← Stack ← OverlayTutorialScope ← WillPopScope ← FadeTransition ←
I/flutter (10861):     KeyedSubtree-[<1>] ← Stack ← AnimatedSwitcher ← TutorialOverlay ← Stack ← _BodyBuilder ←
I/flutter (10861):     MediaQuery ← ⋯
I/flutter (10861):   parentData: not positioned; offset=Offset(0.0, 0.0) (can use size)
I/flutter (10861):   constraints: BoxConstraints(0.0<=w<=411.4, 0.0<=h<=741.7)
I/flutter (10861):   size: Size(411.4, 741.7)
I/flutter (10861):   context: _OverlayTutorialBackbone
I/flutter (10861):   overlayColor: Color(0x8a000000)
I/flutter (10861):   enabled: true
I/flutter (10861):   has onEntryRectCalculated
I/flutter (10861): This RenderObject had the following descendants (showing up to depth 5):
I/flutter (10861):     child: RenderPadding#e84b1 relayoutBoundary=up6
I/flutter (10861):       child: RenderStack#c0c96 relayoutBoundary=up7
I/flutter (10861):         child 1: RenderConstrainedBox#0f194 relayoutBoundary=up8
I/flutter (10861):           child: RenderAbsorbPointer#b927f
I/flutter (10861):         child 2: RenderStack#4778c relayoutBoundary=up8
I/flutter (10861):           child 1: RenderAnimatedOpacity#df290 relayoutBoundary=up9
I/flutter (10861):             child: RenderStack#bfc9c relayoutBoundary=up10
I/flutter (10861):           child 2: RenderAnimatedOpacity#970d4 relayoutBoundary=up9
I/flutter (10861):             child: RenderStack#0420c relayoutBoundary=up10 NEEDS-PAINT
I/flutter (10861):         child 3: RenderPositionedBox#4a15f relayoutBoundary=up8
I/flutter (10861):           child: RenderPadding#d4280 relayoutBoundary=up9
I/flutter (10861):             child: _RenderOverlayTutorialHole#bd316 relayoutBoundary=up10
I/flutter (10861): ════════════════════════════════════════════════════════════════════════════════════════════════════
E/flutter (10861): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Cannot get renderObject of inactive element.
E/flutter (10861): In order for an element to have a valid renderObject, it must be active, which means it is part of the tree.
E/flutter (10861): Instead, this element is in the _ElementLifecycle.defunct state.
E/flutter (10861): If you called this method from a State object, consider guarding it with State.mounted.
E/flutter (10861): The findRenderObject() method was called for the following element:
E/flutter (10861):   SingleChildRenderObjectElement#00ffd(DEFUNCT)
E/flutter (10861): #0      Element.findRenderObject.<anonymous closure>
package:flutter/…/widgets/framework.dart:3885
E/flutter (10861): #1      Element.findRenderObject
package:flutter/…/widgets/framework.dart:3898
E/flutter (10861): #2      OverlayTutorialScopeModel.computeRect
package:overlay_tutorial/…/model/overlay_tutorial_scope_model.dart:11
E/flutter (10861): #3      _OverlayTutorialScopeState._checkIsParentRectUpdated.<anonymous closure>
package:overlay_tutorial/…/widgets/overlay_tutorial_scope.dart:53
E/flutter (10861): #4      Iterable.any (dart:core/iterable.dart:378:15)
E/flutter (10861): #5      _OverlayTutorialScopeState._checkIsParentRectUpdated
package:overlay_tutorial/…/widgets/overlay_tutorial_scope.dart:52
E/flutter (10861): #6      _OverlayTutorialScopeState._updateChildren.<anonymous closure>
package:overlay_tutorial/…/widgets/overlay_tutorial_scope.dart:45
E/flutter (10861): #7      _OverlayTutorialScopeState._updateChildren.<anonymous closure>
package:overlay_tutorial/…/widgets/overlay_tutorial_scope.dart:41
E/flutter (10861): #8      SchedulerBinding._invokeFrameCallback
package:flutter/…/scheduler/binding.dart:1143
E/flutter (10861): #9      SchedulerBinding.handleDrawFrame
package:flutter/…/scheduler/binding.dart:1088
E/flutter (10861): #10     SchedulerBinding._handleDrawFrame
package:flutter/…/scheduler/binding.dart:996
E/flutter (10861): #11     _rootRun (dart:async/zone.dart:1428:13)
E/flutter (10861): #12     _CustomZone.run (dart:async/zone.dart:1328:19)
E/flutter (10861): #13     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
E/flutter (10861): #14     _invoke (dart:ui/hooks.dart:166:10)
E/flutter (10861): #15     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270:5)
E/flutter (10861): #16     _drawFrame (dart:ui/hooks.dart:129:31)
E/flutter (10861):
```

</details>

**Comment by TabooSun** [comment]
What is the version of your `overlay_tutorial` package? I can't reproduce on my side.

**Comment by sukaper** [comment]
It's 2.0.4

**Comment by TabooSun** [comment]
Please provide a minimum reproducible code.

**Comment by sukaper** [comment]
After snooping around, it seems that the behavior of `findRenderObject()` changed following flutter 2.5. It might no longer return just null and can also throw errors.  https://github.com/flutter/flutter/blob/83dfb2237a22ad92c38e345b3aa85aeecae732aa/packages/flutter/lib/src/widgets/framework.dart#L3843

So this line here on tag v2.0.4
https://github.com/TabooSun/overlay_tutorial/blob/768c49d48a62eb3f8d0704569303b342962600b2/lib/src/model/overlay_tutorial_scope_model.dart#L11
should get wrapped with a try-catch block which seems to fix the issue. I took a look at the current master branch but it seems that the line got removed with commit 2c8ccf13388368a218739d2b2503eaa819a87c4c so I didn't send a PR.

**Comment by TabooSun** [comment]
In this case, since I can't reproduce from my side, can you try if the current master branch which has the line removed works for you? If it works, then I can just publish it.

**Comment by sukaper** [comment]
I gave 2c8ccf13388368a218739d2b2503eaa819a87c4c a shot and this time I got two error logs. One while calling `findAncestorStateOfType()` at
https://github.com/TabooSun/overlay_tutorial/blob/2c8ccf13388368a218739d2b2503eaa819a87c4c/lib/src/widgets/overlay_tutorial_hole.dart#L110
with the logs
```
E/flutter (18179): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Looking up a deactivated widget's ancestor is unsafe.
E/flutter (18179): At this point the state of the widget's element tree is no longer stable.
E/flutter (18179): To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.
E/flutter (18179): #0      Element._debugCheckStateIsActiveForAncestorLookup.<anonymous closure>
package:flutter/…/widgets/framework.dart:4032
E/flutter (18179): #1      Element._debugCheckStateIsActiveForAncestorLookup
package:flutter/…/widgets/framework.dart:4046
E/flutter (18179): #2      Element.findAncestorStateOfType
package:flutter/…/widgets/framework.dart:4093
E/flutter (18179): #3      _RenderOverlayTutorialHole.updateChildRect
package:overlay_tutorial/…/widgets/overlay_tutorial_hole.dart:112
E/flutter (18179): #4      OverlayTutorialScopeModel.updateRectConfiguration
package:overlay_tutorial/…/model/overlay_tutorial_scope_model.dart:22
E/flutter (18179): #5      _OverlayTutorialScopeState._updateChildren.<anonymous closure>.<anonymous closure>
package:overlay_tutorial/…/widgets/overlay_tutorial_scope.dart:52
E/flutter (18179): #6      Iterable.forEach (dart:core/iterable.dart:279:35)
E/flutter (18179): #7      _OverlayTutorialScopeState._updateChildren.<anonymous closure>
package:overlay_tutorial/…/widgets/overlay_tutorial_scope.dart:51
E/flutter (18179): #8      _OverlayTutorialScopeState._updateChildren.<anonymous closure>
package:overlay_tutorial/…/widgets/overlay_tutorial_scope.dart:46
E/flutter (18179): #9      SchedulerBinding._invokeFrameCallback
package:flutter/…/scheduler/binding.dart:1143
E/flutter (18179): #10     SchedulerBinding.handleDrawFrame
package:flutter/…/scheduler/binding.dart:1088
E/flutter (18179): #11     SchedulerBinding._handleDrawFrame
package:flutter/…/scheduler/binding.dart:996
E/flutter (18179): #12     _rootRun (dart:async/zone.dart:1428:13)
E/flutter (18179): #13     _CustomZone.run (dart:async/zone.dart:1328:19)
E/flutter (18179): #14     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
E/flutter (18179): #15     _invoke (dart:ui/hooks.dart:166:10)
E/flutter (18179): #16     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270:5)
E/flutter (18179): #17     _drawFrame (dart:ui/hooks.dart:129:31)
```
And another while calling `localToGlobal()` at
https://github.com/TabooSun/overlay_tutorial/blob/2c8ccf13388368a218739d2b2503eaa819a87c4c/lib/src/widgets/overlay_tutorial_hole.dart#L139
```
E/flutter (19901): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: 'package:flutter/src/rendering/object.dart': Failed assertion: line 2475 pos 12: 'attached': is not true.
E/flutter (19901): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
E/flutter (19901): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
E/flutter (19901): #2      RenderObject.getTransformTo
package:flutter/…/rendering/object.dart:2475
E/flutter (19901): #3      RenderBox.localToGlobal
package:flutter/…/rendering/box.dart:2550
E/flutter (19901): #4      _RenderOverlayTutorialHole.computeChildRect
package:overlay_tutorial/…/widgets/overlay_tutorial_hole.dart:145
E/flutter (19901): #5      OverlayTutorialScopeModel.checkShouldRebuild
package:overlay_tutorial/…/model/overlay_tutorial_scope_model.dart:18
E/flutter (19901): #6      _OverlayTutorialScopeState._checkIsParentRectUpdated.<anonymous closure>
package:overlay_tutorial/…/widgets/overlay_tutorial_scope.dart:61
E/flutter (19901): #7      Iterable.any (dart:core/iterable.dart:378:15)
E/flutter (19901): #8      _OverlayTutorialScopeState._checkIsParentRectUpdated
package:overlay_tutorial/…/widgets/overlay_tutorial_scope.dart:61
E/flutter (19901): #9      _OverlayTutorialScopeState._updateChildren.<anonymous closure>
package:overlay_tutorial/…/widgets/overlay_tutorial_scope.dart:50
E/flutter (19901): #10     _OverlayTutorialScopeState._updateChildren.<anonymous closure>
package:overlay_tutorial/…/widgets/overlay_tutorial_scope.dart:46
E/flutter (19901): #11     SchedulerBinding._invokeFrameCallback
package:flutter/…/scheduler/binding.dart:1143
E/flutter (19901): #12     SchedulerBinding.handleDrawFrame
package:flutter/…/scheduler/binding.dart:1088
E/flutter (19901): #13     SchedulerBinding._handleDrawFrame
package:flutter/…/scheduler/binding.dart:996
E/flutter (19901): #14     _rootRun (dart:async/zone.dart:1428:13)
E/flutter (19901): #15     _CustomZone.run (dart:async/zone.dart:1328:19)
E/flutter (19901): #16     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
E/flutter (19901): #17     _invoke (dart:ui/hooks.dart:166:10)
E/flutter (19901): #18     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270:5)
E/flutter (19901): #19     _drawFrame (dart:ui/hooks.dart:129:31)
```
I tried just wrapping these two in try-catch blocks for an easy fix but what happened was the framerate plummeted to the point nothing was moving.
Sorry for not being able to provide reproducible code but I think I'll just be using the current 2.0.4 with the try-catch around `findRenderObject()`

**Comment by TabooSun** [comment]
I am pretty curious why this would happen. Did you set `enabled` to false when the widget being wrapped by `OverlayTutorial` is disposed? Because as stated in the error, the widget is disposed, that's the reason Flutter could not retrieve the position and its size.

**Comment by sukaper** [comment]
I do have it set to `enabled`. And as for the code, I am currently generating `OverlayTutorialHole` and listening for the user to tap within the hole. After a hole gets tapped, the next hole is drawn for the next tutorial spot. All using the same `OverlayTutorialScope`. I use `GlobalKey` to find out where my widget is and generate `OverlayTutorialHole` based on that.
I had suspicions where when the hole gets destroyed, after a user tap, `postFrameCallback` could be trying to access the now disposed `OverlayTutorialHole` but sadly I didn't manage to properly test this out since a quick try-catch fixed it. 

And thanks for the package. Forgot to add that to my last comment.

**Comment by TabooSun** [comment]
> And thanks for the package.

You are welcome.

I would be very happy to help you out with fixing your issue if you are able to create a dummy project and reproduce it in the dummy project.

Do re-open this issue if you are able to do so in the future.
